node{
  stage('SCM Checout'){
   
  git 'https://github.com/sidharthvijayakumar/java-tomcat-maven-example'
  }
  stage('Build'){
     def mvnHome = tool name: 'Maven', type: 'maven'
    sh "${mvnHome}/bin/mvn -f java-tomcat-maven-example/pom.xml clean install"
    
  }
  stage("Deploy"){
    sshagent(['tomcat']) {
    sh "scp -o StrictHostKeyChecking=no /var/lib/jenkins/workspace/java-tomcat-maven-example/java-tomcat-maven-example/target/*.war ec2-user@18.188.209.227:/home/ec2-user/tomcat/webapps"
  }
  }   
}
