node{
  stage('SCM Checout'){
   
  git 'https://github.com/sidharthvijayakumar/java-tomcat-maven-example'
  }
  stage('Build'){
     def mvnHome = tool name: 'Maven', type: 'maven'
    sh "${mvnHome}/bin/mvn -f java-tomcat-maven-example/pom.xml clean install"
    
  }
   stage("publish to s3") {
      
  s3Upload(file:'var/lib/jenkins/workspace/java-tomcat-maven-example/java-tomcat-maven-example/target/*.war', bucket:'s3artifactsforjenkins', path:'target')
    
  } 
  
  stage("Deploy"){
    sshagent(['tomcat']) {
    sh "scp -o StrictHostKeyChecking=no /var/lib/jenkins/workspace/java-tomcat-maven-example/java-tomcat-maven-example/target/*.war ec2-user@3.137.141.24:/home/ec2-user/tomcat/webapps"
  }
  }   
}
